// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserVersionMessage.proto

package com.game.proto;

public final class UserVersionMessage {
  private UserVersionMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.game.proto.Protos}
   *
   * <pre>
   * 枚举类型
   * Req 2xx 客户端请求服务器
   * Res 1xx 服务器相应客户端
   * </pre>
   */
  public enum Protos
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ReqUserVersion = 100202;</code>
     *
     * <pre>
     * 100  201  100表示大模块  2 表示客户端发送  01 表示具体子模块
     * </pre>
     */
    ReqUserVersion(0, 100202),
    /**
     * <code>ResUserVersion = 100102;</code>
     *
     * <pre>
     * 100  101  100表示大模块  1 表示服务端发送  01 表示具体子模块
     * </pre>
     */
    ResUserVersion(1, 100102),
    ;

    /**
     * <code>ReqUserVersion = 100202;</code>
     *
     * <pre>
     * 100  201  100表示大模块  2 表示客户端发送  01 表示具体子模块
     * </pre>
     */
    public static final int ReqUserVersion_VALUE = 100202;
    /**
     * <code>ResUserVersion = 100102;</code>
     *
     * <pre>
     * 100  101  100表示大模块  1 表示服务端发送  01 表示具体子模块
     * </pre>
     */
    public static final int ResUserVersion_VALUE = 100102;


    public final int getNumber() { return value; }

    public static Protos valueOf(int value) {
      switch (value) {
        case 100202: return ReqUserVersion;
        case 100102: return ResUserVersion;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Protos>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Protos>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Protos>() {
            public Protos findValueByNumber(int number) {
              return Protos.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.proto.UserVersionMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Protos[] VALUES = values();

    public static Protos valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Protos(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.game.proto.Protos)
  }

  public interface ReqUserVersionMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.game.proto.Protos msgID = 1 [default = ReqUserVersion];
    /**
     * <code>required .com.game.proto.Protos msgID = 1 [default = ReqUserVersion];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    boolean hasMsgID();
    /**
     * <code>required .com.game.proto.Protos msgID = 1 [default = ReqUserVersion];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
        com.game.proto.UserVersionMessage.Protos getMsgID();

    // optional int64 sendFrom = 2;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    boolean hasSendFrom();
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    long getSendFrom();

    // optional int64 sendTo = 3;
    /**
     * <code>optional int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    boolean hasSendTo();
    /**
     * <code>optional int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    long getSendTo();

    // required int32 version = 4;
    /**
     * <code>required int32 version = 4;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 4;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    int getVersion();
  }
  /**
   * Protobuf type {@code com.game.proto.ReqUserVersionMessage}
   */
  public static final class ReqUserVersionMessage extends
      com.google.protobuf.GeneratedMessage
      implements ReqUserVersionMessageOrBuilder {
    // Use ReqUserVersionMessage.newBuilder() to construct.
    private ReqUserVersionMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqUserVersionMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqUserVersionMessage defaultInstance;
    public static ReqUserVersionMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ReqUserVersionMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqUserVersionMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
                        com.game.proto.UserVersionMessage.Protos value = com.game.proto.UserVersionMessage.Protos.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sendFrom_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sendTo_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              version_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.UserVersionMessage.internal_static_com_game_proto_ReqUserVersionMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.UserVersionMessage.internal_static_com_game_proto_ReqUserVersionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.UserVersionMessage.ReqUserVersionMessage.class, com.game.proto.UserVersionMessage.ReqUserVersionMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqUserVersionMessage> PARSER =
        new com.google.protobuf.AbstractParser<ReqUserVersionMessage>() {
      public ReqUserVersionMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqUserVersionMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqUserVersionMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.game.proto.Protos msgID = 1 [default = ReqUserVersion];
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.game.proto.UserVersionMessage.Protos msgID_;
    /**
     * <code>required .com.game.proto.Protos msgID = 1 [default = ReqUserVersion];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.game.proto.Protos msgID = 1 [default = ReqUserVersion];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public com.game.proto.UserVersionMessage.Protos getMsgID() {
      return msgID_;
    }

    // optional int64 sendFrom = 2;
    public static final int SENDFROM_FIELD_NUMBER = 2;
    private long sendFrom_;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public boolean hasSendFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public long getSendFrom() {
      return sendFrom_;
    }

    // optional int64 sendTo = 3;
    public static final int SENDTO_FIELD_NUMBER = 3;
    private long sendTo_;
    /**
     * <code>optional int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public boolean hasSendTo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public long getSendTo() {
      return sendTo_;
    }

    // required int32 version = 4;
    public static final int VERSION_FIELD_NUMBER = 4;
    private int version_;
    /**
     * <code>required int32 version = 4;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 version = 4;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    private void initFields() {
      msgID_ = com.game.proto.UserVersionMessage.Protos.ReqUserVersion;
      sendFrom_ = 0L;
      sendTo_ = 0L;
      version_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sendFrom_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, sendTo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, version_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sendFrom_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sendTo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, version_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.proto.UserVersionMessage.ReqUserVersionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.UserVersionMessage.ReqUserVersionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.UserVersionMessage.ReqUserVersionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.UserVersionMessage.ReqUserVersionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.UserVersionMessage.ReqUserVersionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.UserVersionMessage.ReqUserVersionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.proto.UserVersionMessage.ReqUserVersionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.proto.UserVersionMessage.ReqUserVersionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.proto.UserVersionMessage.ReqUserVersionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.UserVersionMessage.ReqUserVersionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.proto.UserVersionMessage.ReqUserVersionMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.proto.ReqUserVersionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.proto.UserVersionMessage.ReqUserVersionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  com.game.proto.UserVersionMessage.internal_static_com_game_proto_ReqUserVersionMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  com.game.proto.UserVersionMessage.internal_static_com_game_proto_ReqUserVersionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.proto.UserVersionMessage.ReqUserVersionMessage.class, com.game.proto.UserVersionMessage.ReqUserVersionMessage.Builder.class);
      }

      // Construct using com.game.proto.UserVersionMessage.ReqUserVersionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = com.game.proto.UserVersionMessage.Protos.ReqUserVersion;
        bitField0_ = (bitField0_ & ~0x00000001);
        sendFrom_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        sendTo_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  com.game.proto.UserVersionMessage.internal_static_com_game_proto_ReqUserVersionMessage_descriptor;
      }

      public com.game.proto.UserVersionMessage.ReqUserVersionMessage getDefaultInstanceForType() {
        return  com.game.proto.UserVersionMessage.ReqUserVersionMessage.getDefaultInstance();
      }

      public com.game.proto.UserVersionMessage.ReqUserVersionMessage build() {
                com.game.proto.UserVersionMessage.ReqUserVersionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.proto.UserVersionMessage.ReqUserVersionMessage buildPartial() {
                com.game.proto.UserVersionMessage.ReqUserVersionMessage result = new com.game.proto.UserVersionMessage.ReqUserVersionMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sendFrom_ = sendFrom_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sendTo_ = sendTo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.version_ = version_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.proto.UserVersionMessage.ReqUserVersionMessage) {
          return mergeFrom((com.game.proto.UserVersionMessage.ReqUserVersionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.proto.UserVersionMessage.ReqUserVersionMessage other) {
        if (other == com.game.proto.UserVersionMessage.ReqUserVersionMessage.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasSendFrom()) {
          setSendFrom(other.getSendFrom());
        }
        if (other.hasSendTo()) {
          setSendTo(other.getSendTo());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgID()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                com.game.proto.UserVersionMessage.ReqUserVersionMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.proto.UserVersionMessage.ReqUserVersionMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.game.proto.Protos msgID = 1 [default = ReqUserVersion];
      private com.game.proto.UserVersionMessage.Protos msgID_ = com.game.proto.UserVersionMessage.Protos.ReqUserVersion;
      /**
       * <code>required .com.game.proto.Protos msgID = 1 [default = ReqUserVersion];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.game.proto.Protos msgID = 1 [default = ReqUserVersion];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public com.game.proto.UserVersionMessage.Protos getMsgID() {
        return msgID_;
      }
      /**
       * <code>required .com.game.proto.Protos msgID = 1 [default = ReqUserVersion];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder setMsgID(com.game.proto.UserVersionMessage.Protos value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.game.proto.Protos msgID = 1 [default = ReqUserVersion];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = com.game.proto.UserVersionMessage.Protos.ReqUserVersion;
        onChanged();
        return this;
      }

      // optional int64 sendFrom = 2;
      private long sendFrom_ ;
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public boolean hasSendFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public long getSendFrom() {
        return sendFrom_;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder setSendFrom(long value) {
        bitField0_ |= 0x00000002;
        sendFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder clearSendFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sendFrom_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 sendTo = 3;
      private long sendTo_ ;
      /**
       * <code>optional int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public boolean hasSendTo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public long getSendTo() {
        return sendTo_;
      }
      /**
       * <code>optional int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder setSendTo(long value) {
        bitField0_ |= 0x00000004;
        sendTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder clearSendTo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sendTo_ = 0L;
        onChanged();
        return this;
      }

      // required int32 version = 4;
      private int version_ ;
      /**
       * <code>required int32 version = 4;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 version = 4;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 4;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000008;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 4;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        version_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.proto.ReqUserVersionMessage)
    }

    static {
      defaultInstance = new ReqUserVersionMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.proto.ReqUserVersionMessage)
  }

  public interface ResUserVersionMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.game.proto.Protos msgID = 1 [default = ResUserVersion];
    /**
     * <code>required .com.game.proto.Protos msgID = 1 [default = ResUserVersion];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    boolean hasMsgID();
    /**
     * <code>required .com.game.proto.Protos msgID = 1 [default = ResUserVersion];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
        com.game.proto.UserVersionMessage.Protos getMsgID();

    // optional int64 sendFrom = 2;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    boolean hasSendFrom();
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    long getSendFrom();

    // optional int64 sendTo = 3;
    /**
     * <code>optional int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    boolean hasSendTo();
    /**
     * <code>optional int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    long getSendTo();

    // required int32 pstrIP = 4;
    /**
     * <code>required int32 pstrIP = 4;</code>
     */
    boolean hasPstrIP();
    /**
     * <code>required int32 pstrIP = 4;</code>
     */
    int getPstrIP();
  }
  /**
   * Protobuf type {@code com.game.proto.ResUserVersionMessage}
   */
  public static final class ResUserVersionMessage extends
      com.google.protobuf.GeneratedMessage
      implements ResUserVersionMessageOrBuilder {
    // Use ResUserVersionMessage.newBuilder() to construct.
    private ResUserVersionMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResUserVersionMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResUserVersionMessage defaultInstance;
    public static ResUserVersionMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ResUserVersionMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResUserVersionMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
                        com.game.proto.UserVersionMessage.Protos value = com.game.proto.UserVersionMessage.Protos.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sendFrom_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sendTo_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              pstrIP_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.UserVersionMessage.internal_static_com_game_proto_ResUserVersionMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.UserVersionMessage.internal_static_com_game_proto_ResUserVersionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.UserVersionMessage.ResUserVersionMessage.class, com.game.proto.UserVersionMessage.ResUserVersionMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ResUserVersionMessage> PARSER =
        new com.google.protobuf.AbstractParser<ResUserVersionMessage>() {
      public ResUserVersionMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResUserVersionMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResUserVersionMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.game.proto.Protos msgID = 1 [default = ResUserVersion];
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.game.proto.UserVersionMessage.Protos msgID_;
    /**
     * <code>required .com.game.proto.Protos msgID = 1 [default = ResUserVersion];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.game.proto.Protos msgID = 1 [default = ResUserVersion];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public com.game.proto.UserVersionMessage.Protos getMsgID() {
      return msgID_;
    }

    // optional int64 sendFrom = 2;
    public static final int SENDFROM_FIELD_NUMBER = 2;
    private long sendFrom_;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public boolean hasSendFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public long getSendFrom() {
      return sendFrom_;
    }

    // optional int64 sendTo = 3;
    public static final int SENDTO_FIELD_NUMBER = 3;
    private long sendTo_;
    /**
     * <code>optional int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public boolean hasSendTo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public long getSendTo() {
      return sendTo_;
    }

    // required int32 pstrIP = 4;
    public static final int PSTRIP_FIELD_NUMBER = 4;
    private int pstrIP_;
    /**
     * <code>required int32 pstrIP = 4;</code>
     */
    public boolean hasPstrIP() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 pstrIP = 4;</code>
     */
    public int getPstrIP() {
      return pstrIP_;
    }

    private void initFields() {
      msgID_ = com.game.proto.UserVersionMessage.Protos.ResUserVersion;
      sendFrom_ = 0L;
      sendTo_ = 0L;
      pstrIP_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPstrIP()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sendFrom_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, sendTo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, pstrIP_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sendFrom_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sendTo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pstrIP_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.proto.UserVersionMessage.ResUserVersionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.UserVersionMessage.ResUserVersionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.UserVersionMessage.ResUserVersionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.UserVersionMessage.ResUserVersionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.UserVersionMessage.ResUserVersionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.UserVersionMessage.ResUserVersionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.proto.UserVersionMessage.ResUserVersionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.proto.UserVersionMessage.ResUserVersionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.proto.UserVersionMessage.ResUserVersionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.UserVersionMessage.ResUserVersionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.proto.UserVersionMessage.ResUserVersionMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.proto.ResUserVersionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.proto.UserVersionMessage.ResUserVersionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  com.game.proto.UserVersionMessage.internal_static_com_game_proto_ResUserVersionMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  com.game.proto.UserVersionMessage.internal_static_com_game_proto_ResUserVersionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.proto.UserVersionMessage.ResUserVersionMessage.class, com.game.proto.UserVersionMessage.ResUserVersionMessage.Builder.class);
      }

      // Construct using com.game.proto.UserVersionMessage.ResUserVersionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = com.game.proto.UserVersionMessage.Protos.ResUserVersion;
        bitField0_ = (bitField0_ & ~0x00000001);
        sendFrom_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        sendTo_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        pstrIP_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  com.game.proto.UserVersionMessage.internal_static_com_game_proto_ResUserVersionMessage_descriptor;
      }

      public com.game.proto.UserVersionMessage.ResUserVersionMessage getDefaultInstanceForType() {
        return  com.game.proto.UserVersionMessage.ResUserVersionMessage.getDefaultInstance();
      }

      public com.game.proto.UserVersionMessage.ResUserVersionMessage build() {
                com.game.proto.UserVersionMessage.ResUserVersionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.proto.UserVersionMessage.ResUserVersionMessage buildPartial() {
                com.game.proto.UserVersionMessage.ResUserVersionMessage result = new com.game.proto.UserVersionMessage.ResUserVersionMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sendFrom_ = sendFrom_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sendTo_ = sendTo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pstrIP_ = pstrIP_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.proto.UserVersionMessage.ResUserVersionMessage) {
          return mergeFrom((com.game.proto.UserVersionMessage.ResUserVersionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.proto.UserVersionMessage.ResUserVersionMessage other) {
        if (other == com.game.proto.UserVersionMessage.ResUserVersionMessage.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasSendFrom()) {
          setSendFrom(other.getSendFrom());
        }
        if (other.hasSendTo()) {
          setSendTo(other.getSendTo());
        }
        if (other.hasPstrIP()) {
          setPstrIP(other.getPstrIP());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgID()) {
          
          return false;
        }
        if (!hasPstrIP()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                com.game.proto.UserVersionMessage.ResUserVersionMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.proto.UserVersionMessage.ResUserVersionMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.game.proto.Protos msgID = 1 [default = ResUserVersion];
      private com.game.proto.UserVersionMessage.Protos msgID_ = com.game.proto.UserVersionMessage.Protos.ResUserVersion;
      /**
       * <code>required .com.game.proto.Protos msgID = 1 [default = ResUserVersion];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.game.proto.Protos msgID = 1 [default = ResUserVersion];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public com.game.proto.UserVersionMessage.Protos getMsgID() {
        return msgID_;
      }
      /**
       * <code>required .com.game.proto.Protos msgID = 1 [default = ResUserVersion];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder setMsgID(com.game.proto.UserVersionMessage.Protos value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.game.proto.Protos msgID = 1 [default = ResUserVersion];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = com.game.proto.UserVersionMessage.Protos.ResUserVersion;
        onChanged();
        return this;
      }

      // optional int64 sendFrom = 2;
      private long sendFrom_ ;
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public boolean hasSendFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public long getSendFrom() {
        return sendFrom_;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder setSendFrom(long value) {
        bitField0_ |= 0x00000002;
        sendFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder clearSendFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sendFrom_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 sendTo = 3;
      private long sendTo_ ;
      /**
       * <code>optional int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public boolean hasSendTo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public long getSendTo() {
        return sendTo_;
      }
      /**
       * <code>optional int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder setSendTo(long value) {
        bitField0_ |= 0x00000004;
        sendTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder clearSendTo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sendTo_ = 0L;
        onChanged();
        return this;
      }

      // required int32 pstrIP = 4;
      private int pstrIP_ ;
      /**
       * <code>required int32 pstrIP = 4;</code>
       */
      public boolean hasPstrIP() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 pstrIP = 4;</code>
       */
      public int getPstrIP() {
        return pstrIP_;
      }
      /**
       * <code>required int32 pstrIP = 4;</code>
       */
      public Builder setPstrIP(int value) {
        bitField0_ |= 0x00000008;
        pstrIP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pstrIP = 4;</code>
       */
      public Builder clearPstrIP() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pstrIP_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.proto.ResUserVersionMessage)
    }

    static {
      defaultInstance = new ResUserVersionMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.proto.ResUserVersionMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_proto_ReqUserVersionMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_proto_ReqUserVersionMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_proto_ResUserVersionMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_proto_ResUserVersionMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030UserVersionMessage.proto\022\016com.game.pro" +
      "to\"\201\001\n\025ReqUserVersionMessage\0225\n\005msgID\030\001 " +
      "\002(\0162\026.com.game.proto.Protos:\016ReqUserVers" +
      "ion\022\020\n\010sendFrom\030\002 \001(\003\022\016\n\006sendTo\030\003 \001(\003\022\017\n" +
      "\007version\030\004 \002(\005\"\200\001\n\025ResUserVersionMessage" +
      "\0225\n\005msgID\030\001 \002(\0162\026.com.game.proto.Protos:" +
      "\016ResUserVersion\022\020\n\010sendFrom\030\002 \001(\003\022\016\n\006sen" +
      "dTo\030\003 \001(\003\022\016\n\006pstrIP\030\004 \002(\005*4\n\006Protos\022\024\n\016R" +
      "eqUserVersion\020\352\216\006\022\024\n\016ResUserVersion\020\206\216\006"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_game_proto_ReqUserVersionMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_game_proto_ReqUserVersionMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_proto_ReqUserVersionMessage_descriptor,
              new java.lang.String[] { "MsgID", "SendFrom", "SendTo", "Version", });
          internal_static_com_game_proto_ResUserVersionMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_game_proto_ResUserVersionMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_proto_ResUserVersionMessage_descriptor,
              new java.lang.String[] { "MsgID", "SendFrom", "SendTo", "PstrIP", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
