// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginMessage.proto

package com.game.proto;

public final class LoginMessage {
  private LoginMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.game.proto.Protos}
   *
   * <pre>
   * 枚举类型
   * Req 2xx 客户端请求服务器
   * Res 1xx 服务器相应客户端
   * </pre>
   */
  public enum Protos
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ReqLogin = 100201;</code>
     *
     * <pre>
     * 100  201  100表示大模块  2 表示客户端发送  01 表示具体子模块
     * </pre>
     */
    ReqLogin(0, 100201),
    /**
     * <code>ResLogin = 100101;</code>
     *
     * <pre>
     * 100  101  100表示大模块  1 表示服务端发送  01 表示具体子模块
     * </pre>
     */
    ResLogin(1, 100101),
    ;

    /**
     * <code>ReqLogin = 100201;</code>
     *
     * <pre>
     * 100  201  100表示大模块  2 表示客户端发送  01 表示具体子模块
     * </pre>
     */
    public static final int ReqLogin_VALUE = 100201;
    /**
     * <code>ResLogin = 100101;</code>
     *
     * <pre>
     * 100  101  100表示大模块  1 表示服务端发送  01 表示具体子模块
     * </pre>
     */
    public static final int ResLogin_VALUE = 100101;


    public final int getNumber() { return value; }

    public static Protos valueOf(int value) {
      switch (value) {
        case 100201: return ReqLogin;
        case 100101: return ResLogin;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Protos>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Protos>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Protos>() {
            public Protos findValueByNumber(int number) {
              return Protos.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.proto.LoginMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Protos[] VALUES = values();

    public static Protos valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Protos(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.game.proto.Protos)
  }

  public interface ReqLoginMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.game.proto.Protos msgID = 1 [default = ReqLogin];
    /**
     * <code>optional .com.game.proto.Protos msgID = 1 [default = ReqLogin];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    boolean hasMsgID();
    /**
     * <code>optional .com.game.proto.Protos msgID = 1 [default = ReqLogin];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
        com.game.proto.LoginMessage.Protos getMsgID();

    // optional int64 sendFrom = 2;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    boolean hasSendFrom();
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    long getSendFrom();

    // repeated int64 sendTo = 3;
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    java.util.List<java.lang.Long> getSendToList();
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    int getSendToCount();
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    long getSendTo(int index);

    // required string username = 4;
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    boolean hasUsername();
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    java.lang.String getUsername();
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // required string password = 5;
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码   
     * </pre>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码   
     * </pre>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码   
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code com.game.proto.ReqLoginMessage}
   */
  public static final class ReqLoginMessage extends
      com.google.protobuf.GeneratedMessage
      implements ReqLoginMessageOrBuilder {
    // Use ReqLoginMessage.newBuilder() to construct.
    private ReqLoginMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqLoginMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqLoginMessage defaultInstance;
    public static ReqLoginMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ReqLoginMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqLoginMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
                        com.game.proto.LoginMessage.Protos value = com.game.proto.LoginMessage.Protos.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sendFrom_ = input.readInt64();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sendTo_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              sendTo_.add(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                sendTo_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                sendTo_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              username_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              password_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = java.util.Collections.unmodifiableList(sendTo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.LoginMessage.internal_static_com_game_proto_ReqLoginMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.LoginMessage.internal_static_com_game_proto_ReqLoginMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.LoginMessage.ReqLoginMessage.class, com.game.proto.LoginMessage.ReqLoginMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqLoginMessage> PARSER =
        new com.google.protobuf.AbstractParser<ReqLoginMessage>() {
      public ReqLoginMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqLoginMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqLoginMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.game.proto.Protos msgID = 1 [default = ReqLogin];
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.game.proto.LoginMessage.Protos msgID_;
    /**
     * <code>optional .com.game.proto.Protos msgID = 1 [default = ReqLogin];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.game.proto.Protos msgID = 1 [default = ReqLogin];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public com.game.proto.LoginMessage.Protos getMsgID() {
      return msgID_;
    }

    // optional int64 sendFrom = 2;
    public static final int SENDFROM_FIELD_NUMBER = 2;
    private long sendFrom_;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public boolean hasSendFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public long getSendFrom() {
      return sendFrom_;
    }

    // repeated int64 sendTo = 3;
    public static final int SENDTO_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Long> sendTo_;
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public java.util.List<java.lang.Long>
        getSendToList() {
      return sendTo_;
    }
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public int getSendToCount() {
      return sendTo_.size();
    }
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public long getSendTo(int index) {
      return sendTo_.get(index);
    }

    // required string username = 4;
    public static final int USERNAME_FIELD_NUMBER = 4;
    private java.lang.Object username_;
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string password = 5;
    public static final int PASSWORD_FIELD_NUMBER = 5;
    private java.lang.Object password_;
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码   
     * </pre>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码   
     * </pre>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码   
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgID_ = com.game.proto.LoginMessage.Protos.ReqLogin;
      sendFrom_ = 0L;
      sendTo_ = java.util.Collections.emptyList();
      username_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sendFrom_);
      }
      for (int i = 0; i < sendTo_.size(); i++) {
        output.writeInt64(3, sendTo_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sendFrom_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sendTo_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(sendTo_.get(i));
        }
        size += dataSize;
        size += 1 * getSendToList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.proto.LoginMessage.ReqLoginMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.LoginMessage.ReqLoginMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.LoginMessage.ReqLoginMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.LoginMessage.ReqLoginMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.LoginMessage.ReqLoginMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.LoginMessage.ReqLoginMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.proto.LoginMessage.ReqLoginMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.proto.LoginMessage.ReqLoginMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.proto.LoginMessage.ReqLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.LoginMessage.ReqLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.proto.LoginMessage.ReqLoginMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.proto.ReqLoginMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.proto.LoginMessage.ReqLoginMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  com.game.proto.LoginMessage.internal_static_com_game_proto_ReqLoginMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  com.game.proto.LoginMessage.internal_static_com_game_proto_ReqLoginMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.proto.LoginMessage.ReqLoginMessage.class, com.game.proto.LoginMessage.ReqLoginMessage.Builder.class);
      }

      // Construct using com.game.proto.LoginMessage.ReqLoginMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = com.game.proto.LoginMessage.Protos.ReqLogin;
        bitField0_ = (bitField0_ & ~0x00000001);
        sendFrom_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        sendTo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  com.game.proto.LoginMessage.internal_static_com_game_proto_ReqLoginMessage_descriptor;
      }

      public com.game.proto.LoginMessage.ReqLoginMessage getDefaultInstanceForType() {
        return  com.game.proto.LoginMessage.ReqLoginMessage.getDefaultInstance();
      }

      public com.game.proto.LoginMessage.ReqLoginMessage build() {
                com.game.proto.LoginMessage.ReqLoginMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.proto.LoginMessage.ReqLoginMessage buildPartial() {
                com.game.proto.LoginMessage.ReqLoginMessage result = new com.game.proto.LoginMessage.ReqLoginMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sendFrom_ = sendFrom_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = java.util.Collections.unmodifiableList(sendTo_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.sendTo_ = sendTo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.proto.LoginMessage.ReqLoginMessage) {
          return mergeFrom((com.game.proto.LoginMessage.ReqLoginMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.proto.LoginMessage.ReqLoginMessage other) {
        if (other == com.game.proto.LoginMessage.ReqLoginMessage.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasSendFrom()) {
          setSendFrom(other.getSendFrom());
        }
        if (!other.sendTo_.isEmpty()) {
          if (sendTo_.isEmpty()) {
            sendTo_ = other.sendTo_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSendToIsMutable();
            sendTo_.addAll(other.sendTo_);
          }
          onChanged();
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000008;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000010;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                com.game.proto.LoginMessage.ReqLoginMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.proto.LoginMessage.ReqLoginMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.game.proto.Protos msgID = 1 [default = ReqLogin];
      private com.game.proto.LoginMessage.Protos msgID_ = com.game.proto.LoginMessage.Protos.ReqLogin;
      /**
       * <code>optional .com.game.proto.Protos msgID = 1 [default = ReqLogin];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.game.proto.Protos msgID = 1 [default = ReqLogin];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public com.game.proto.LoginMessage.Protos getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .com.game.proto.Protos msgID = 1 [default = ReqLogin];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder setMsgID(com.game.proto.LoginMessage.Protos value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.game.proto.Protos msgID = 1 [default = ReqLogin];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = com.game.proto.LoginMessage.Protos.ReqLogin;
        onChanged();
        return this;
      }

      // optional int64 sendFrom = 2;
      private long sendFrom_ ;
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public boolean hasSendFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public long getSendFrom() {
        return sendFrom_;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder setSendFrom(long value) {
        bitField0_ |= 0x00000002;
        sendFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder clearSendFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sendFrom_ = 0L;
        onChanged();
        return this;
      }

      // repeated int64 sendTo = 3;
      private java.util.List<java.lang.Long> sendTo_ = java.util.Collections.emptyList();
      private void ensureSendToIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = new java.util.ArrayList<java.lang.Long>(sendTo_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public java.util.List<java.lang.Long>
          getSendToList() {
        return java.util.Collections.unmodifiableList(sendTo_);
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public int getSendToCount() {
        return sendTo_.size();
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public long getSendTo(int index) {
        return sendTo_.get(index);
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder setSendTo(
          int index, long value) {
        ensureSendToIsMutable();
        sendTo_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder addSendTo(long value) {
        ensureSendToIsMutable();
        sendTo_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder addAllSendTo(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSendToIsMutable();
        super.addAll(values, sendTo_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder clearSendTo() {
        sendTo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // required string username = 4;
      private java.lang.Object username_ = "";
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000008);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        username_ = value;
        onChanged();
        return this;
      }

      // required string password = 5;
      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码   
       * </pre>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码   
       * </pre>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码   
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码   
       * </pre>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码   
       * </pre>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000010);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码   
       * </pre>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.proto.ReqLoginMessage)
    }

    static {
      defaultInstance = new ReqLoginMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.proto.ReqLoginMessage)
  }

  public interface ResLoginMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.game.proto.Protos msgID = 1 [default = ResLogin];
    /**
     * <code>optional .com.game.proto.Protos msgID = 1 [default = ResLogin];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    boolean hasMsgID();
    /**
     * <code>optional .com.game.proto.Protos msgID = 1 [default = ResLogin];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
        com.game.proto.LoginMessage.Protos getMsgID();

    // optional int64 sendFrom = 2;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    boolean hasSendFrom();
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    long getSendFrom();

    // repeated int64 sendTo = 3;
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    java.util.List<java.lang.Long> getSendToList();
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    int getSendToCount();
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    long getSendTo(int index);

    // required string username = 4;
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    boolean hasUsername();
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    java.lang.String getUsername();
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // required string password = 5;
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码  
     * </pre>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码  
     * </pre>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码  
     * </pre>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code com.game.proto.ResLoginMessage}
   */
  public static final class ResLoginMessage extends
      com.google.protobuf.GeneratedMessage
      implements ResLoginMessageOrBuilder {
    // Use ResLoginMessage.newBuilder() to construct.
    private ResLoginMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResLoginMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResLoginMessage defaultInstance;
    public static ResLoginMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ResLoginMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResLoginMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
                        com.game.proto.LoginMessage.Protos value = com.game.proto.LoginMessage.Protos.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sendFrom_ = input.readInt64();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sendTo_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              sendTo_.add(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                sendTo_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                sendTo_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              username_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              password_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = java.util.Collections.unmodifiableList(sendTo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.LoginMessage.internal_static_com_game_proto_ResLoginMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.LoginMessage.internal_static_com_game_proto_ResLoginMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.LoginMessage.ResLoginMessage.class, com.game.proto.LoginMessage.ResLoginMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ResLoginMessage> PARSER =
        new com.google.protobuf.AbstractParser<ResLoginMessage>() {
      public ResLoginMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResLoginMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResLoginMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.game.proto.Protos msgID = 1 [default = ResLogin];
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.game.proto.LoginMessage.Protos msgID_;
    /**
     * <code>optional .com.game.proto.Protos msgID = 1 [default = ResLogin];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.game.proto.Protos msgID = 1 [default = ResLogin];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public com.game.proto.LoginMessage.Protos getMsgID() {
      return msgID_;
    }

    // optional int64 sendFrom = 2;
    public static final int SENDFROM_FIELD_NUMBER = 2;
    private long sendFrom_;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public boolean hasSendFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public long getSendFrom() {
      return sendFrom_;
    }

    // repeated int64 sendTo = 3;
    public static final int SENDTO_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Long> sendTo_;
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public java.util.List<java.lang.Long>
        getSendToList() {
      return sendTo_;
    }
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public int getSendToCount() {
      return sendTo_.size();
    }
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public long getSendTo(int index) {
      return sendTo_.get(index);
    }

    // required string username = 4;
    public static final int USERNAME_FIELD_NUMBER = 4;
    private java.lang.Object username_;
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string username = 4;</code>
     *
     * <pre>
     * 帐号   
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string password = 5;
    public static final int PASSWORD_FIELD_NUMBER = 5;
    private java.lang.Object password_;
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码  
     * </pre>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码  
     * </pre>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 5;</code>
     *
     * <pre>
     * 密码  
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgID_ = com.game.proto.LoginMessage.Protos.ResLogin;
      sendFrom_ = 0L;
      sendTo_ = java.util.Collections.emptyList();
      username_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sendFrom_);
      }
      for (int i = 0; i < sendTo_.size(); i++) {
        output.writeInt64(3, sendTo_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sendFrom_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sendTo_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(sendTo_.get(i));
        }
        size += dataSize;
        size += 1 * getSendToList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.proto.LoginMessage.ResLoginMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.LoginMessage.ResLoginMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.LoginMessage.ResLoginMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.LoginMessage.ResLoginMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.LoginMessage.ResLoginMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.LoginMessage.ResLoginMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.proto.LoginMessage.ResLoginMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.proto.LoginMessage.ResLoginMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.proto.LoginMessage.ResLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.LoginMessage.ResLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.proto.LoginMessage.ResLoginMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.proto.ResLoginMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.proto.LoginMessage.ResLoginMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  com.game.proto.LoginMessage.internal_static_com_game_proto_ResLoginMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  com.game.proto.LoginMessage.internal_static_com_game_proto_ResLoginMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.proto.LoginMessage.ResLoginMessage.class, com.game.proto.LoginMessage.ResLoginMessage.Builder.class);
      }

      // Construct using com.game.proto.LoginMessage.ResLoginMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = com.game.proto.LoginMessage.Protos.ResLogin;
        bitField0_ = (bitField0_ & ~0x00000001);
        sendFrom_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        sendTo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  com.game.proto.LoginMessage.internal_static_com_game_proto_ResLoginMessage_descriptor;
      }

      public com.game.proto.LoginMessage.ResLoginMessage getDefaultInstanceForType() {
        return  com.game.proto.LoginMessage.ResLoginMessage.getDefaultInstance();
      }

      public com.game.proto.LoginMessage.ResLoginMessage build() {
                com.game.proto.LoginMessage.ResLoginMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.proto.LoginMessage.ResLoginMessage buildPartial() {
                com.game.proto.LoginMessage.ResLoginMessage result = new com.game.proto.LoginMessage.ResLoginMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sendFrom_ = sendFrom_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = java.util.Collections.unmodifiableList(sendTo_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.sendTo_ = sendTo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.proto.LoginMessage.ResLoginMessage) {
          return mergeFrom((com.game.proto.LoginMessage.ResLoginMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.proto.LoginMessage.ResLoginMessage other) {
        if (other == com.game.proto.LoginMessage.ResLoginMessage.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasSendFrom()) {
          setSendFrom(other.getSendFrom());
        }
        if (!other.sendTo_.isEmpty()) {
          if (sendTo_.isEmpty()) {
            sendTo_ = other.sendTo_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSendToIsMutable();
            sendTo_.addAll(other.sendTo_);
          }
          onChanged();
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000008;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000010;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                com.game.proto.LoginMessage.ResLoginMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.proto.LoginMessage.ResLoginMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.game.proto.Protos msgID = 1 [default = ResLogin];
      private com.game.proto.LoginMessage.Protos msgID_ = com.game.proto.LoginMessage.Protos.ResLogin;
      /**
       * <code>optional .com.game.proto.Protos msgID = 1 [default = ResLogin];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.game.proto.Protos msgID = 1 [default = ResLogin];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public com.game.proto.LoginMessage.Protos getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .com.game.proto.Protos msgID = 1 [default = ResLogin];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder setMsgID(com.game.proto.LoginMessage.Protos value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.game.proto.Protos msgID = 1 [default = ResLogin];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = com.game.proto.LoginMessage.Protos.ResLogin;
        onChanged();
        return this;
      }

      // optional int64 sendFrom = 2;
      private long sendFrom_ ;
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public boolean hasSendFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public long getSendFrom() {
        return sendFrom_;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder setSendFrom(long value) {
        bitField0_ |= 0x00000002;
        sendFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder clearSendFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sendFrom_ = 0L;
        onChanged();
        return this;
      }

      // repeated int64 sendTo = 3;
      private java.util.List<java.lang.Long> sendTo_ = java.util.Collections.emptyList();
      private void ensureSendToIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = new java.util.ArrayList<java.lang.Long>(sendTo_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public java.util.List<java.lang.Long>
          getSendToList() {
        return java.util.Collections.unmodifiableList(sendTo_);
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public int getSendToCount() {
        return sendTo_.size();
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public long getSendTo(int index) {
        return sendTo_.get(index);
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder setSendTo(
          int index, long value) {
        ensureSendToIsMutable();
        sendTo_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder addSendTo(long value) {
        ensureSendToIsMutable();
        sendTo_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder addAllSendTo(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSendToIsMutable();
        super.addAll(values, sendTo_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder clearSendTo() {
        sendTo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // required string username = 4;
      private java.lang.Object username_ = "";
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000008);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 4;</code>
       *
       * <pre>
       * 帐号   
       * </pre>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        username_ = value;
        onChanged();
        return this;
      }

      // required string password = 5;
      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码  
       * </pre>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码  
       * </pre>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码  
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码  
       * </pre>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码  
       * </pre>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000010);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 5;</code>
       *
       * <pre>
       * 密码  
       * </pre>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.proto.ResLoginMessage)
    }

    static {
      defaultInstance = new ResLoginMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.proto.ResLoginMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_proto_ReqLoginMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_proto_ReqLoginMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_proto_ResLoginMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_proto_ResLoginMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LoginMessage.proto\022\016com.game.proto\"\210\001\n" +
      "\017ReqLoginMessage\022/\n\005msgID\030\001 \001(\0162\026.com.ga" +
      "me.proto.Protos:\010ReqLogin\022\020\n\010sendFrom\030\002 " +
      "\001(\003\022\016\n\006sendTo\030\003 \003(\003\022\020\n\010username\030\004 \002(\t\022\020\n" +
      "\010password\030\005 \002(\t\"\210\001\n\017ResLoginMessage\022/\n\005m" +
      "sgID\030\001 \001(\0162\026.com.game.proto.Protos:\010ResL" +
      "ogin\022\020\n\010sendFrom\030\002 \001(\003\022\016\n\006sendTo\030\003 \003(\003\022\020" +
      "\n\010username\030\004 \002(\t\022\020\n\010password\030\005 \002(\t*(\n\006Pr" +
      "otos\022\016\n\010ReqLogin\020\351\216\006\022\016\n\010ResLogin\020\205\216\006"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_game_proto_ReqLoginMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_game_proto_ReqLoginMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_proto_ReqLoginMessage_descriptor,
              new java.lang.String[] { "MsgID", "SendFrom", "SendTo", "Username", "Password", });
          internal_static_com_game_proto_ResLoginMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_game_proto_ResLoginMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_proto_ResLoginMessage_descriptor,
              new java.lang.String[] { "MsgID", "SendFrom", "SendTo", "Username", "Password", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
