// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterDataMessage.proto

package com.game.proto;

public final class RegisterDataMessage {
  private RegisterDataMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.game.proto.Protos_RegisterData}
   */
  public enum Protos_RegisterData
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GDRegisterData = 111101;</code>
     *
     * <pre>
     * GameServer 2 DataServer 注册请求
     * </pre>
     */
    GDRegisterData(0, 111101),
    /**
     * <code>DGRegisterData = 111201;</code>
     *
     * <pre>
     * DataServer 2 GameServer 注册响应
     * </pre>
     */
    DGRegisterData(1, 111201),
    ;

    /**
     * <code>GDRegisterData = 111101;</code>
     *
     * <pre>
     * GameServer 2 DataServer 注册请求
     * </pre>
     */
    public static final int GDRegisterData_VALUE = 111101;
    /**
     * <code>DGRegisterData = 111201;</code>
     *
     * <pre>
     * DataServer 2 GameServer 注册响应
     * </pre>
     */
    public static final int DGRegisterData_VALUE = 111201;


    public final int getNumber() { return value; }

    public static Protos_RegisterData valueOf(int value) {
      switch (value) {
        case 111101: return GDRegisterData;
        case 111201: return DGRegisterData;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Protos_RegisterData>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Protos_RegisterData>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Protos_RegisterData>() {
            public Protos_RegisterData findValueByNumber(int number) {
              return Protos_RegisterData.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.proto.RegisterDataMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final Protos_RegisterData[] VALUES = values();

    public static Protos_RegisterData valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Protos_RegisterData(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.game.proto.Protos_RegisterData)
  }

  public interface GDRegisterDataMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.game.proto.Protos_RegisterData msgID = 1 [default = GDRegisterData];
    /**
     * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = GDRegisterData];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    boolean hasMsgID();
    /**
     * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = GDRegisterData];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    com.game.proto.RegisterDataMessage.Protos_RegisterData getMsgID();

    // optional int64 sendFrom = 2;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    boolean hasSendFrom();
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    long getSendFrom();

    // repeated int64 sendTo = 3;
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    java.util.List<java.lang.Long> getSendToList();
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    int getSendToCount();
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    long getSendTo(int index);

    // required int32 serverId = 4;
    /**
     * <code>required int32 serverId = 4;</code>
     *
     * <pre>
     * 服务器编号
     * </pre>
     */
    boolean hasServerId();
    /**
     * <code>required int32 serverId = 4;</code>
     *
     * <pre>
     * 服务器编号
     * </pre>
     */
    int getServerId();

    // required string serverName = 5;
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    boolean hasServerName();
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    java.lang.String getServerName();
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    com.google.protobuf.ByteString
        getServerNameBytes();

    // optional string messageData = 6;
    /**
     * <code>optional string messageData = 6;</code>
     *
     * <pre>
     * 消息数据
     * </pre>
     */
    boolean hasMessageData();
    /**
     * <code>optional string messageData = 6;</code>
     *
     * <pre>
     * 消息数据
     * </pre>
     */
    java.lang.String getMessageData();
    /**
     * <code>optional string messageData = 6;</code>
     *
     * <pre>
     * 消息数据
     * </pre>
     */
    com.google.protobuf.ByteString
        getMessageDataBytes();
  }
  /**
   * Protobuf type {@code com.game.proto.GDRegisterDataMessage}
   */
  public static final class GDRegisterDataMessage extends
      com.google.protobuf.GeneratedMessage
      implements GDRegisterDataMessageOrBuilder {
    // Use GDRegisterDataMessage.newBuilder() to construct.
    private GDRegisterDataMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GDRegisterDataMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GDRegisterDataMessage defaultInstance;
    public static GDRegisterDataMessage getDefaultInstance() {
      return defaultInstance;
    }

    public GDRegisterDataMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GDRegisterDataMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.game.proto.RegisterDataMessage.Protos_RegisterData value = com.game.proto.RegisterDataMessage.Protos_RegisterData.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sendFrom_ = input.readInt64();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sendTo_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              sendTo_.add(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                sendTo_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                sendTo_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              serverId_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              serverName_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              messageData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = java.util.Collections.unmodifiableList(sendTo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.RegisterDataMessage.internal_static_com_game_proto_GDRegisterDataMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.RegisterDataMessage.internal_static_com_game_proto_GDRegisterDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.RegisterDataMessage.GDRegisterDataMessage.class, com.game.proto.RegisterDataMessage.GDRegisterDataMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<GDRegisterDataMessage> PARSER =
        new com.google.protobuf.AbstractParser<GDRegisterDataMessage>() {
      public GDRegisterDataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GDRegisterDataMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GDRegisterDataMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.game.proto.Protos_RegisterData msgID = 1 [default = GDRegisterData];
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.game.proto.RegisterDataMessage.Protos_RegisterData msgID_;
    /**
     * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = GDRegisterData];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = GDRegisterData];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public com.game.proto.RegisterDataMessage.Protos_RegisterData getMsgID() {
      return msgID_;
    }

    // optional int64 sendFrom = 2;
    public static final int SENDFROM_FIELD_NUMBER = 2;
    private long sendFrom_;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public boolean hasSendFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public long getSendFrom() {
      return sendFrom_;
    }

    // repeated int64 sendTo = 3;
    public static final int SENDTO_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Long> sendTo_;
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public java.util.List<java.lang.Long>
        getSendToList() {
      return sendTo_;
    }
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public int getSendToCount() {
      return sendTo_.size();
    }
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public long getSendTo(int index) {
      return sendTo_.get(index);
    }

    // required int32 serverId = 4;
    public static final int SERVERID_FIELD_NUMBER = 4;
    private int serverId_;
    /**
     * <code>required int32 serverId = 4;</code>
     *
     * <pre>
     * 服务器编号
     * </pre>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 serverId = 4;</code>
     *
     * <pre>
     * 服务器编号
     * </pre>
     */
    public int getServerId() {
      return serverId_;
    }

    // required string serverName = 5;
    public static final int SERVERNAME_FIELD_NUMBER = 5;
    private java.lang.Object serverName_;
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    public boolean hasServerName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string messageData = 6;
    public static final int MESSAGEDATA_FIELD_NUMBER = 6;
    private java.lang.Object messageData_;
    /**
     * <code>optional string messageData = 6;</code>
     *
     * <pre>
     * 消息数据
     * </pre>
     */
    public boolean hasMessageData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string messageData = 6;</code>
     *
     * <pre>
     * 消息数据
     * </pre>
     */
    public java.lang.String getMessageData() {
      java.lang.Object ref = messageData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string messageData = 6;</code>
     *
     * <pre>
     * 消息数据
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMessageDataBytes() {
      java.lang.Object ref = messageData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgID_ = com.game.proto.RegisterDataMessage.Protos_RegisterData.GDRegisterData;
      sendFrom_ = 0L;
      sendTo_ = java.util.Collections.emptyList();
      serverId_ = 0;
      serverName_ = "";
      messageData_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sendFrom_);
      }
      for (int i = 0; i < sendTo_.size(); i++) {
        output.writeInt64(3, sendTo_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, serverId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getServerNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getMessageDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sendFrom_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sendTo_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(sendTo_.get(i));
        }
        size += dataSize;
        size += 1 * getSendToList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, serverId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getServerNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getMessageDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.proto.RegisterDataMessage.GDRegisterDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.RegisterDataMessage.GDRegisterDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.RegisterDataMessage.GDRegisterDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.RegisterDataMessage.GDRegisterDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.RegisterDataMessage.GDRegisterDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.RegisterDataMessage.GDRegisterDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.proto.RegisterDataMessage.GDRegisterDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.proto.RegisterDataMessage.GDRegisterDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.proto.RegisterDataMessage.GDRegisterDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.RegisterDataMessage.GDRegisterDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.proto.RegisterDataMessage.GDRegisterDataMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.proto.GDRegisterDataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.proto.RegisterDataMessage.GDRegisterDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.proto.RegisterDataMessage.internal_static_com_game_proto_GDRegisterDataMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.proto.RegisterDataMessage.internal_static_com_game_proto_GDRegisterDataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.proto.RegisterDataMessage.GDRegisterDataMessage.class, com.game.proto.RegisterDataMessage.GDRegisterDataMessage.Builder.class);
      }

      // Construct using com.game.proto.RegisterDataMessage.GDRegisterDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = com.game.proto.RegisterDataMessage.Protos_RegisterData.GDRegisterData;
        bitField0_ = (bitField0_ & ~0x00000001);
        sendFrom_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        sendTo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        serverName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        messageData_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.proto.RegisterDataMessage.internal_static_com_game_proto_GDRegisterDataMessage_descriptor;
      }

      public com.game.proto.RegisterDataMessage.GDRegisterDataMessage getDefaultInstanceForType() {
        return com.game.proto.RegisterDataMessage.GDRegisterDataMessage.getDefaultInstance();
      }

      public com.game.proto.RegisterDataMessage.GDRegisterDataMessage build() {
        com.game.proto.RegisterDataMessage.GDRegisterDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.proto.RegisterDataMessage.GDRegisterDataMessage buildPartial() {
        com.game.proto.RegisterDataMessage.GDRegisterDataMessage result = new com.game.proto.RegisterDataMessage.GDRegisterDataMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sendFrom_ = sendFrom_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = java.util.Collections.unmodifiableList(sendTo_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.sendTo_ = sendTo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serverName_ = serverName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.messageData_ = messageData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.proto.RegisterDataMessage.GDRegisterDataMessage) {
          return mergeFrom((com.game.proto.RegisterDataMessage.GDRegisterDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.proto.RegisterDataMessage.GDRegisterDataMessage other) {
        if (other == com.game.proto.RegisterDataMessage.GDRegisterDataMessage.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasSendFrom()) {
          setSendFrom(other.getSendFrom());
        }
        if (!other.sendTo_.isEmpty()) {
          if (sendTo_.isEmpty()) {
            sendTo_ = other.sendTo_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSendToIsMutable();
            sendTo_.addAll(other.sendTo_);
          }
          onChanged();
        }
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasServerName()) {
          bitField0_ |= 0x00000010;
          serverName_ = other.serverName_;
          onChanged();
        }
        if (other.hasMessageData()) {
          bitField0_ |= 0x00000020;
          messageData_ = other.messageData_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerId()) {
          
          return false;
        }
        if (!hasServerName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.proto.RegisterDataMessage.GDRegisterDataMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.proto.RegisterDataMessage.GDRegisterDataMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.game.proto.Protos_RegisterData msgID = 1 [default = GDRegisterData];
      private com.game.proto.RegisterDataMessage.Protos_RegisterData msgID_ = com.game.proto.RegisterDataMessage.Protos_RegisterData.GDRegisterData;
      /**
       * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = GDRegisterData];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = GDRegisterData];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public com.game.proto.RegisterDataMessage.Protos_RegisterData getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = GDRegisterData];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder setMsgID(com.game.proto.RegisterDataMessage.Protos_RegisterData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = GDRegisterData];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = com.game.proto.RegisterDataMessage.Protos_RegisterData.GDRegisterData;
        onChanged();
        return this;
      }

      // optional int64 sendFrom = 2;
      private long sendFrom_ ;
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public boolean hasSendFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public long getSendFrom() {
        return sendFrom_;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder setSendFrom(long value) {
        bitField0_ |= 0x00000002;
        sendFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder clearSendFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sendFrom_ = 0L;
        onChanged();
        return this;
      }

      // repeated int64 sendTo = 3;
      private java.util.List<java.lang.Long> sendTo_ = java.util.Collections.emptyList();
      private void ensureSendToIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = new java.util.ArrayList<java.lang.Long>(sendTo_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public java.util.List<java.lang.Long>
          getSendToList() {
        return java.util.Collections.unmodifiableList(sendTo_);
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public int getSendToCount() {
        return sendTo_.size();
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public long getSendTo(int index) {
        return sendTo_.get(index);
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder setSendTo(
          int index, long value) {
        ensureSendToIsMutable();
        sendTo_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder addSendTo(long value) {
        ensureSendToIsMutable();
        sendTo_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder addAllSendTo(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSendToIsMutable();
        super.addAll(values, sendTo_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder clearSendTo() {
        sendTo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // required int32 serverId = 4;
      private int serverId_ ;
      /**
       * <code>required int32 serverId = 4;</code>
       *
       * <pre>
       * 服务器编号
       * </pre>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 serverId = 4;</code>
       *
       * <pre>
       * 服务器编号
       * </pre>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>required int32 serverId = 4;</code>
       *
       * <pre>
       * 服务器编号
       * </pre>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000008;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverId = 4;</code>
       *
       * <pre>
       * 服务器编号
       * </pre>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serverId_ = 0;
        onChanged();
        return this;
      }

      // required string serverName = 5;
      private java.lang.Object serverName_ = "";
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public boolean hasServerName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public java.lang.String getServerName() {
        java.lang.Object ref = serverName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        java.lang.Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public Builder setServerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        serverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public Builder clearServerName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        serverName_ = getDefaultInstance().getServerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        serverName_ = value;
        onChanged();
        return this;
      }

      // optional string messageData = 6;
      private java.lang.Object messageData_ = "";
      /**
       * <code>optional string messageData = 6;</code>
       *
       * <pre>
       * 消息数据
       * </pre>
       */
      public boolean hasMessageData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string messageData = 6;</code>
       *
       * <pre>
       * 消息数据
       * </pre>
       */
      public java.lang.String getMessageData() {
        java.lang.Object ref = messageData_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          messageData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string messageData = 6;</code>
       *
       * <pre>
       * 消息数据
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMessageDataBytes() {
        java.lang.Object ref = messageData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string messageData = 6;</code>
       *
       * <pre>
       * 消息数据
       * </pre>
       */
      public Builder setMessageData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        messageData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string messageData = 6;</code>
       *
       * <pre>
       * 消息数据
       * </pre>
       */
      public Builder clearMessageData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        messageData_ = getDefaultInstance().getMessageData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string messageData = 6;</code>
       *
       * <pre>
       * 消息数据
       * </pre>
       */
      public Builder setMessageDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        messageData_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.proto.GDRegisterDataMessage)
    }

    static {
      defaultInstance = new GDRegisterDataMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.proto.GDRegisterDataMessage)
  }

  public interface DGRegisterDataMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.game.proto.Protos_RegisterData msgID = 1 [default = DGRegisterData];
    /**
     * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = DGRegisterData];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    boolean hasMsgID();
    /**
     * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = DGRegisterData];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    com.game.proto.RegisterDataMessage.Protos_RegisterData getMsgID();

    // optional int64 sendFrom = 2;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    boolean hasSendFrom();
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    long getSendFrom();

    // repeated int64 sendTo = 3;
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    java.util.List<java.lang.Long> getSendToList();
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    int getSendToCount();
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    long getSendTo(int index);

    // required int32 serverId = 4;
    /**
     * <code>required int32 serverId = 4;</code>
     *
     * <pre>
     * 服务器编号
     * </pre>
     */
    boolean hasServerId();
    /**
     * <code>required int32 serverId = 4;</code>
     *
     * <pre>
     * 服务器编号
     * </pre>
     */
    int getServerId();

    // required string serverName = 5;
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    boolean hasServerName();
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    java.lang.String getServerName();
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    com.google.protobuf.ByteString
        getServerNameBytes();
  }
  /**
   * Protobuf type {@code com.game.proto.DGRegisterDataMessage}
   */
  public static final class DGRegisterDataMessage extends
      com.google.protobuf.GeneratedMessage
      implements DGRegisterDataMessageOrBuilder {
    // Use DGRegisterDataMessage.newBuilder() to construct.
    private DGRegisterDataMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DGRegisterDataMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DGRegisterDataMessage defaultInstance;
    public static DGRegisterDataMessage getDefaultInstance() {
      return defaultInstance;
    }

    public DGRegisterDataMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DGRegisterDataMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.game.proto.RegisterDataMessage.Protos_RegisterData value = com.game.proto.RegisterDataMessage.Protos_RegisterData.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgID_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sendFrom_ = input.readInt64();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sendTo_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              sendTo_.add(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                sendTo_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                sendTo_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              serverId_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              serverName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = java.util.Collections.unmodifiableList(sendTo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.proto.RegisterDataMessage.internal_static_com_game_proto_DGRegisterDataMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.proto.RegisterDataMessage.internal_static_com_game_proto_DGRegisterDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.proto.RegisterDataMessage.DGRegisterDataMessage.class, com.game.proto.RegisterDataMessage.DGRegisterDataMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<DGRegisterDataMessage> PARSER =
        new com.google.protobuf.AbstractParser<DGRegisterDataMessage>() {
      public DGRegisterDataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DGRegisterDataMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DGRegisterDataMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.game.proto.Protos_RegisterData msgID = 1 [default = DGRegisterData];
    public static final int MSGID_FIELD_NUMBER = 1;
    private com.game.proto.RegisterDataMessage.Protos_RegisterData msgID_;
    /**
     * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = DGRegisterData];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public boolean hasMsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = DGRegisterData];</code>
     *
     * <pre>
     * 消息ID,虽然是optional,但必须定义default枚举值
     * </pre>
     */
    public com.game.proto.RegisterDataMessage.Protos_RegisterData getMsgID() {
      return msgID_;
    }

    // optional int64 sendFrom = 2;
    public static final int SENDFROM_FIELD_NUMBER = 2;
    private long sendFrom_;
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public boolean hasSendFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 sendFrom = 2;</code>
     *
     * <pre>
     * 消息发送者
     * </pre>
     */
    public long getSendFrom() {
      return sendFrom_;
    }

    // repeated int64 sendTo = 3;
    public static final int SENDTO_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Long> sendTo_;
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public java.util.List<java.lang.Long>
        getSendToList() {
      return sendTo_;
    }
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public int getSendToCount() {
      return sendTo_.size();
    }
    /**
     * <code>repeated int64 sendTo = 3;</code>
     *
     * <pre>
     * 消息接受者,允许多个接收者
     * </pre>
     */
    public long getSendTo(int index) {
      return sendTo_.get(index);
    }

    // required int32 serverId = 4;
    public static final int SERVERID_FIELD_NUMBER = 4;
    private int serverId_;
    /**
     * <code>required int32 serverId = 4;</code>
     *
     * <pre>
     * 服务器编号
     * </pre>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 serverId = 4;</code>
     *
     * <pre>
     * 服务器编号
     * </pre>
     */
    public int getServerId() {
      return serverId_;
    }

    // required string serverName = 5;
    public static final int SERVERNAME_FIELD_NUMBER = 5;
    private java.lang.Object serverName_;
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    public boolean hasServerName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serverName = 5;</code>
     *
     * <pre>
     * 服务器名字
     * </pre>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgID_ = com.game.proto.RegisterDataMessage.Protos_RegisterData.DGRegisterData;
      sendFrom_ = 0L;
      sendTo_ = java.util.Collections.emptyList();
      serverId_ = 0;
      serverName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sendFrom_);
      }
      for (int i = 0; i < sendTo_.size(); i++) {
        output.writeInt64(3, sendTo_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, serverId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getServerNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgID_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sendFrom_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sendTo_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(sendTo_.get(i));
        }
        size += dataSize;
        size += 1 * getSendToList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, serverId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getServerNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.game.proto.RegisterDataMessage.DGRegisterDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.RegisterDataMessage.DGRegisterDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.RegisterDataMessage.DGRegisterDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.proto.RegisterDataMessage.DGRegisterDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.proto.RegisterDataMessage.DGRegisterDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.RegisterDataMessage.DGRegisterDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.game.proto.RegisterDataMessage.DGRegisterDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.game.proto.RegisterDataMessage.DGRegisterDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.game.proto.RegisterDataMessage.DGRegisterDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.game.proto.RegisterDataMessage.DGRegisterDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.proto.RegisterDataMessage.DGRegisterDataMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.proto.DGRegisterDataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.proto.RegisterDataMessage.DGRegisterDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.proto.RegisterDataMessage.internal_static_com_game_proto_DGRegisterDataMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.proto.RegisterDataMessage.internal_static_com_game_proto_DGRegisterDataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.proto.RegisterDataMessage.DGRegisterDataMessage.class, com.game.proto.RegisterDataMessage.DGRegisterDataMessage.Builder.class);
      }

      // Construct using com.game.proto.RegisterDataMessage.DGRegisterDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgID_ = com.game.proto.RegisterDataMessage.Protos_RegisterData.DGRegisterData;
        bitField0_ = (bitField0_ & ~0x00000001);
        sendFrom_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        sendTo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        serverName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.proto.RegisterDataMessage.internal_static_com_game_proto_DGRegisterDataMessage_descriptor;
      }

      public com.game.proto.RegisterDataMessage.DGRegisterDataMessage getDefaultInstanceForType() {
        return com.game.proto.RegisterDataMessage.DGRegisterDataMessage.getDefaultInstance();
      }

      public com.game.proto.RegisterDataMessage.DGRegisterDataMessage build() {
        com.game.proto.RegisterDataMessage.DGRegisterDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.proto.RegisterDataMessage.DGRegisterDataMessage buildPartial() {
        com.game.proto.RegisterDataMessage.DGRegisterDataMessage result = new com.game.proto.RegisterDataMessage.DGRegisterDataMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgID_ = msgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sendFrom_ = sendFrom_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = java.util.Collections.unmodifiableList(sendTo_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.sendTo_ = sendTo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serverName_ = serverName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.proto.RegisterDataMessage.DGRegisterDataMessage) {
          return mergeFrom((com.game.proto.RegisterDataMessage.DGRegisterDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.proto.RegisterDataMessage.DGRegisterDataMessage other) {
        if (other == com.game.proto.RegisterDataMessage.DGRegisterDataMessage.getDefaultInstance()) return this;
        if (other.hasMsgID()) {
          setMsgID(other.getMsgID());
        }
        if (other.hasSendFrom()) {
          setSendFrom(other.getSendFrom());
        }
        if (!other.sendTo_.isEmpty()) {
          if (sendTo_.isEmpty()) {
            sendTo_ = other.sendTo_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSendToIsMutable();
            sendTo_.addAll(other.sendTo_);
          }
          onChanged();
        }
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasServerName()) {
          bitField0_ |= 0x00000010;
          serverName_ = other.serverName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerId()) {
          
          return false;
        }
        if (!hasServerName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.proto.RegisterDataMessage.DGRegisterDataMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.proto.RegisterDataMessage.DGRegisterDataMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.game.proto.Protos_RegisterData msgID = 1 [default = DGRegisterData];
      private com.game.proto.RegisterDataMessage.Protos_RegisterData msgID_ = com.game.proto.RegisterDataMessage.Protos_RegisterData.DGRegisterData;
      /**
       * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = DGRegisterData];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public boolean hasMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = DGRegisterData];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public com.game.proto.RegisterDataMessage.Protos_RegisterData getMsgID() {
        return msgID_;
      }
      /**
       * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = DGRegisterData];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder setMsgID(com.game.proto.RegisterDataMessage.Protos_RegisterData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.game.proto.Protos_RegisterData msgID = 1 [default = DGRegisterData];</code>
       *
       * <pre>
       * 消息ID,虽然是optional,但必须定义default枚举值
       * </pre>
       */
      public Builder clearMsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgID_ = com.game.proto.RegisterDataMessage.Protos_RegisterData.DGRegisterData;
        onChanged();
        return this;
      }

      // optional int64 sendFrom = 2;
      private long sendFrom_ ;
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public boolean hasSendFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public long getSendFrom() {
        return sendFrom_;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder setSendFrom(long value) {
        bitField0_ |= 0x00000002;
        sendFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sendFrom = 2;</code>
       *
       * <pre>
       * 消息发送者
       * </pre>
       */
      public Builder clearSendFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sendFrom_ = 0L;
        onChanged();
        return this;
      }

      // repeated int64 sendTo = 3;
      private java.util.List<java.lang.Long> sendTo_ = java.util.Collections.emptyList();
      private void ensureSendToIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sendTo_ = new java.util.ArrayList<java.lang.Long>(sendTo_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public java.util.List<java.lang.Long>
          getSendToList() {
        return java.util.Collections.unmodifiableList(sendTo_);
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public int getSendToCount() {
        return sendTo_.size();
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public long getSendTo(int index) {
        return sendTo_.get(index);
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder setSendTo(
          int index, long value) {
        ensureSendToIsMutable();
        sendTo_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder addSendTo(long value) {
        ensureSendToIsMutable();
        sendTo_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder addAllSendTo(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSendToIsMutable();
        super.addAll(values, sendTo_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 sendTo = 3;</code>
       *
       * <pre>
       * 消息接受者,允许多个接收者
       * </pre>
       */
      public Builder clearSendTo() {
        sendTo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // required int32 serverId = 4;
      private int serverId_ ;
      /**
       * <code>required int32 serverId = 4;</code>
       *
       * <pre>
       * 服务器编号
       * </pre>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 serverId = 4;</code>
       *
       * <pre>
       * 服务器编号
       * </pre>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>required int32 serverId = 4;</code>
       *
       * <pre>
       * 服务器编号
       * </pre>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000008;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverId = 4;</code>
       *
       * <pre>
       * 服务器编号
       * </pre>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serverId_ = 0;
        onChanged();
        return this;
      }

      // required string serverName = 5;
      private java.lang.Object serverName_ = "";
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public boolean hasServerName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public java.lang.String getServerName() {
        java.lang.Object ref = serverName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        java.lang.Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public Builder setServerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        serverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public Builder clearServerName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        serverName_ = getDefaultInstance().getServerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 5;</code>
       *
       * <pre>
       * 服务器名字
       * </pre>
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        serverName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.game.proto.DGRegisterDataMessage)
    }

    static {
      defaultInstance = new DGRegisterDataMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.game.proto.DGRegisterDataMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_proto_GDRegisterDataMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_proto_GDRegisterDataMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_proto_DGRegisterDataMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_game_proto_DGRegisterDataMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031RegisterDataMessage.proto\022\016com.game.pr" +
      "oto\"\270\001\n\025GDRegisterDataMessage\022B\n\005msgID\030\001" +
      " \001(\0162#.com.game.proto.Protos_RegisterDat" +
      "a:\016GDRegisterData\022\020\n\010sendFrom\030\002 \001(\003\022\016\n\006s" +
      "endTo\030\003 \003(\003\022\020\n\010serverId\030\004 \002(\005\022\022\n\nserverN" +
      "ame\030\005 \002(\t\022\023\n\013messageData\030\006 \001(\t\"\243\001\n\025DGReg" +
      "isterDataMessage\022B\n\005msgID\030\001 \001(\0162#.com.ga" +
      "me.proto.Protos_RegisterData:\016DGRegister" +
      "Data\022\020\n\010sendFrom\030\002 \001(\003\022\016\n\006sendTo\030\003 \003(\003\022\020" +
      "\n\010serverId\030\004 \002(\005\022\022\n\nserverName\030\005 \002(\t*A\n\023",
      "Protos_RegisterData\022\024\n\016GDRegisterData\020\375\343" +
      "\006\022\024\n\016DGRegisterData\020\341\344\006"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_game_proto_GDRegisterDataMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_game_proto_GDRegisterDataMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_proto_GDRegisterDataMessage_descriptor,
              new java.lang.String[] { "MsgID", "SendFrom", "SendTo", "ServerId", "ServerName", "MessageData", });
          internal_static_com_game_proto_DGRegisterDataMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_game_proto_DGRegisterDataMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_game_proto_DGRegisterDataMessage_descriptor,
              new java.lang.String[] { "MsgID", "SendFrom", "SendTo", "ServerId", "ServerName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
